/*
The data dictionary provides context into the important variables that educational components of this survey.

Information such as Gender, Commute time to school, school start age etc will be utilized here.
*/
CREATE VIEW VIETNAM_EDUCATION_EQUALITY AS
SELECT CHILDID,
		FLOOR(AGEMON/12) AS[AGE],
		ROUND,
		T2.REGION_NAME AS [REGION],
		CASE -- CLASSIFY GENDER
			WHEN CHSEX = 1 THEN 'MALE'
			WHEN CHSEX = 2 THEN 'FEMALE'
		ELSE 'UNKNOWN'
		END AS [GENDER],
		COMMSCH AS [SCHOOL_COMMUTE_TIME],
		CASE -- CLASSIFY PREPRIMARY SCHOOL ATTENDANCE
			WHEN PREPRIM = 0 THEN 'NO'
			WHEN PREPRIM = 1 THEN 'YES'
		ELSE 'UNKNOWN'
		END AS [ATTENDED_PREPRIMARY],
		AGEGR1 AS [SCHOOL_START_AGE],
		CASE -- CHILD IN SCHOOL
			WHEN ENROL = 0 THEN 'NO'
			WHEN ENROL = 1 THEN 'YES'
		END AS [IN_SCHOOL],
		CASE -- EDUCATION LEVEL
			WHEN LEVLREAD = 1 THEN 'CANT READ'
			WHEN LEVLREAD = 2 THEN 'READ LETTERS'
			WHEN LEVLREAD = 3 THEN 'READ WORDS'
			WHEN LEVLREAD = 4 THEN 'READ_SENTENCE'
		ELSE 'UNKNOWN'
		END AS [READING_LEVEL],
		CASE
			WHEN LEVLWRIT = 1 THEN 'NO'
			WHEN LEVLWRIT = 2 THEN 'YES_WITHDIFFICULTY'
			WHEN LEVLWRIT = 3 THEN 'YES_WITHOUTDIFFICULTY'

		ELSE 'UNKNOWN'
		END AS [WRITING_LEVEL],
		CASE
			WHEN LITERATE = 0 THEN 'NO'
			WHEN LITERATE = 1 THEN 'YES'
		ELSE 'UNKNOWN'
		END AS [LITERATE]

		FROM [DBO].[VIETNAM] AS T1
		INNER JOIN [DBO].[REGIONDATA] AS T2
		ON T1.REGION = T2.REGION_CODE

